name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe the problem you're trying to solve — not just the solution you have in mind.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What pain point are you experiencing?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds you've tried or alternative approaches?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice-to-have
        - Important
        - Critical
    validations:
      required: true

  - type: dropdown
    id: plan
    attributes:
      label: Your current plan
      options:
        - Free
        - Pro
        - Business
        - Enterprise
